/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tugasgui;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TiketGUI extends javax.swing.JFrame {
String nama;
int umur = 0;
int kategori;
int tiket = 0;
int total;

private void count()
{
     try 
            {
                umur = Integer.parseInt(txtumur.getText());
                if(umur < 17)
                {
                    kategori = 0;
                }
                else if (umur >= 17 && umur <= 25)
                {
                    kategori = 50000;
                }
                else if (umur >=26 && umur <= 35)
                {
                    kategori = 100000;
                }
                 else 
                {
                    kategori = 150000;
                }
                tiket = Integer.parseInt(txtJmlTiket.getText());
                total = kategori * tiket;
                
                txtTot.setText(Integer.toString(total));
            }
    catch (NumberFormatException e)
            {
                System.out.println("Umur dan Jumlah Tiket Harus Berupa Angka. "+e);
                JOptionPane.showMessageDialog(null, "Umur dan Jumlah Tiket Harus Berupa Angka");
            }
}
    /**
     * Creates new form TiketGUI
     */
    public TiketGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtumur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtJmlTiket = new javax.swing.JTextField();
        txtTotal = new javax.swing.JLabel();
        txtRp = new javax.swing.JLabel();
        txtTot = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnamaFocusLost(evt);
            }
        });
        txtnama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnamaMouseClicked(evt);
            }
        });
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel2.setText("Umur");

        txtumur.setText("0");
        txtumur.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtumurFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtumurFocusLost(evt);
            }
        });
        txtumur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtumurActionPerformed(evt);
            }
        });
        txtumur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtumurKeyReleased(evt);
            }
        });

        jLabel3.setText("Jumlah Tiket");

        txtJmlTiket.setText("0");
        txtJmlTiket.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJmlTiketFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJmlTiketFocusLost(evt);
            }
        });
        txtJmlTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlTiketActionPerformed(evt);
            }
        });
        txtJmlTiket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJmlTiketKeyReleased(evt);
            }
        });

        txtTotal.setText("Total");

        txtRp.setText("Rp");

        txtTot.setText("0");
        txtTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotActionPerformed(evt);
            }
        });

        jButton1.setText("simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnama)
                            .addComponent(txtumur, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRp))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJmlTiket)
                            .addComponent(txtTot, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtumur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJmlTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRp)
                    .addComponent(txtTotal))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txtumur.getText().isEmpty()|| txtumur.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,  "Semua Isian Harus Diisi");
        }
        else
        {
            
           if(kategori == 0)
           {
              JOptionPane.showMessageDialog(null,  "Umur Belum Mencukupi"); 
           }
           else
           {
               JOptionPane.showMessageDialog(null,  "Pembayaran Atas Nama " + txtnama.getText() + " Telah Berhasil.\nTotal Pembayaran : Rp " + total );
           }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotActionPerformed

    private void txtJmlTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlTiketActionPerformed

    private void txtJmlTiketFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJmlTiketFocusGained
        // TODO add your handling code here:
        if(txtJmlTiket.getText().equals("0"))
        {
            txtJmlTiket.setText("");
        }
    }//GEN-LAST:event_txtJmlTiketFocusGained

    private void txtJmlTiketFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJmlTiketFocusLost
        // TODO add your handling code here:
         if(txtJmlTiket.getText().equals(""))
        {
            txtJmlTiket.setText("0");
        }
    }//GEN-LAST:event_txtJmlTiketFocusLost

    private void txtJmlTiketKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlTiketKeyReleased
        // TODO add your handling code here:
         if(txtJmlTiket.getText().equals(""))
        {
            txtJmlTiket.setText("0");
        }
        count();
    }//GEN-LAST:event_txtJmlTiketKeyReleased

    private void txtumurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtumurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtumurActionPerformed

    private void txtumurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtumurKeyReleased
        // TODO add your handling code here:
         if(txtumur.getText().equals(""))
        {
            txtumur.setText("0");
        }
        count();
        
    }//GEN-LAST:event_txtumurKeyReleased

    private void txtumurFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtumurFocusGained
        // TODO add your handling code here:
        if(txtumur.getText().equals("0"))
        {
            txtumur.setText("");
        };
    }//GEN-LAST:event_txtumurFocusGained

    private void txtumurFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtumurFocusLost
        // TODO add your handling code here:
        if(txtumur.getText().equals(""))
        {
            txtumur.setText("0");
        }
    }//GEN-LAST:event_txtumurFocusLost

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaFocusGained

    private void txtnamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusLost
        // TODO add your handling code here:
         if(txtnama.getText().equals(""))
        {
            txtnama.setText(nama);
        }
    }//GEN-LAST:event_txtnamaFocusLost

    private void txtnamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamaMouseClicked
        // TODO add your handling code here:
        if(txtnama.getText().equals(nama))
        {
            txtnama.setText("");
        }
    }//GEN-LAST:event_txtnamaMouseClicked
                  

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
           nama = txtnama.getText();
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiketGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtJmlTiket;
    private javax.swing.JLabel txtRp;
    private javax.swing.JTextField txtTot;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtumur;
    // End of variables declaration//GEN-END:variables
}
